### ISSUE TITLE
Migrate CLI to click

### ISSUE THREAD

**Issue by Stedders** [synek/git-plan#40]

**Comment by synek** [comment]
I wanted to use click initially, but I couldn't get it to work with dependency injection.

I think the current `argparse` setup works pretty well, and if we want to make it more elegant we can move `Command.register_subparser()` to be a decorator on the `Command` class or something.

Is there any advantage that Click offers that we definitely need to have for git-plan?

**Comment by synek** [comment]
Closing this for now.
