### ISSUE TITLE
Add pre-commit/pre-push hooks

### ISSUE THREAD

**Issue by Stedders** [synek/git-plan#43]
Run any changed tests before commit, run tox before push

**Comment by synek** [comment]
This will involve putting the hook files in some top-level directory, and then adding a script that will move them into `.git/` right?

**Comment by synek** [comment]
I came across this [script](https://gist.github.com/carlos-jenkins/89da9dcf9e0d528ac978311938aade43) which might be useful

**Comment by Stedders** [comment]
There is a fairly comprehensive set of tooling at https://pre-commit.com/, makes life a lot easier.

**Comment by Stedders** [comment]
I'll look at this next.

My usual stack is...

pre-commit:
- Format with [black](https://github.com/psf/black)
- Lint with [pylint](https://github.com/PyCQA/pylint/)
- Run any changed tests with pytest

pre-push:
- Run the entire tox test suite

The action will halt if any of them fail

**Comment by synek** [comment]
Can we drop black? I'd prefer to keep the codebase looking like "natural" Python for readability.

Also, can we get type checking in? I want to keep this fully-typed if possible.

**Comment by Stedders** [comment]
A person after my own heart.

[mypy](https://github.com/python/mypy) ok for typing or do you prefer something else?

**Comment by synek** [comment]
Mypy sounds good, let's do it

**Comment by Stedders** [comment]
This will add further "dev" packages, i.e. packages that are only required development.

I usually distinguish these by having a requirements_dev.txt file, the thinking being that if someone wants to install from source they can simply run `pip install .` and then `pip install -r requirements_dev.txt` if they want to contribute.

There are [other patterns](https://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments/20720019#20720019) to manage this as well.

At the moment we have the single requirements.txt file which contains `-e .` and tox.

I think it would better to distinguish between an install from local source and install with the intention to develop/contribute. I also quite like the pattern give above.

My plan would be to have tox, pylint and mypy in the dev path, remove the current requirements.txt and update the README with instructions.



Do you have a preference/thoughts?

**Comment by synek** [comment]
My intention was that `requirements.txt` is for development, and `setup.py` is for regular use.

Install for usage uses `setup.py` (see [here](https://github.com/synek/git-plan/blob/master/Makefile#L39)) and install for develop uses `requirements.txt`, which is basically `setup.py` + dev dependencies.

It sounds like you suggested pattern would mean we remove `-e .` from the `requirements.txt` file and rename it `requirements_dev.txt`, right?

If so then I'm all for it.

**Comment by Stedders** [comment]
I was just updating the documentation and noticed it is all HTML, do you want to keep it that way? I find MarkDown a lot easier for documentation.

**Comment by synek** [comment]
I think we can actually mix-and-match HTML and markdown, which I didn't realise before, so I'm fine with switching to markdown.

But we'll need to keep HTML for any text which is centre-aligned, because Markdown doesn't support that (as far as I know?)
