### ISSUE TITLE
The plan directory should not be in `.git/`

### ISSUE THREAD

**Issue by synek** [synek/git-plan#61]
Maybe `.plan/` will be better?

```
.plan
├── EDIT_TEMPLATE
├── PLAN_TEMPLATE
├── plans
       └── commit-1616487506.txt
```

**Comment by Stedders** [comment]
I was looking at this a little last night with regards to https://github.com/synek/git-plan/issues/45.

Where would you expect .plan to live?

I started thinking that we should set up an area in the user's home drive. We could use a .local or .config folder in the user dir to store it as mentioned [here](https://askubuntu.com/questions/14535/whats-the-local-folder-for-in-my-home-directory).

```
~
├─.local
       ├─git-plan
                ├─templates
                ├          └── EDIT
                ├          └── PLAN
                ├          └── CLIENT-EDIT (custom)
                ├── plans
                ├          └── commit-1616487506.txt
                ├── config.yml
```

**Comment by synek** [comment]
I was thinking that `.plan/` would be in the repository root directory. Each project has its own `.plan/`. The benefits are 1) planfiles are stored in-project, which is clean and safe, and 2) template files can be committed to source control if teams want to share them. One disadvantage is that teams would have to put `.plan/plans` in their `.gitignore` instead of the cleaner `.plan/`, but for me that's not a big deal.

We can also support `.local/` level templates, and load the template with a priority like in-project > local > default.

**Comment by synek** [comment]
Heads up @Stedders:

I closed this in #69 

Also, maybe we should use `.config/git-plan` to store per-user configuration files (templates and `config.yaml`). That's the recommended place for it, as far as I know?

**Comment by Stedders** [comment]
Hey @synek, agreed. That was my intention with the custom plans.

I've been a bit tired up with stuff this week, but I will try to raise a PR including a ~/.comfig structure on Sunday.

**Comment by synek** [comment]
No worries, take your time. Looking forward to seeing the PR.

I'm going to put some thought into #63 because it unlocks future functionality, and I'll also get #67, #70, and #66 done over the weekend.

**Comment by synek** [comment]
Also while I have you @Stedders I renamed `master` to `main` because I kept mis-typing it. Sorry for the hassle.
