### ISSUE TITLE
[Bug] `RuntimeError` is raised when not in a git repository

### ISSUE THREAD

**Issue by synek** [synek/git-plan#79]
Describe the bug
================
When running `git-plan` or `gp` outside of a git repository, a `RuntimeError` is shown with a stack trace.

To Reproduce
============
1. `pip install git-plan`
2. `git-plan list` (in a directory without a `.git/` directory)

Expected behavior
=================
A useful error message should be shown.

There is already a `NotAGitRepository` Exception in the stack trace, so we should just catch that in the right place and display an error message.

**Comment by JBizarri** [comment]
@synek I just opened PR #80
